(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e" "-f"
"-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z" "abs" "accept"
"alarm" "atan2" "bind" "binmode" "bless" "break" "caller" "chdir" "chmod"
"chomp" "chop" "chown" "chr" "chroot" "close" "closedir" "connect"
"continue" "cos" "crypt" "dbmclose" "dbmopen" "defined" "delete" "die" "do"
"dump" "each" "endgrent" "endhostent" "endnetent" "endprotoent" "endpwent"
"endservent" "eof" "eval" "exec" "exists" "exit" "exp" "fcntl" "fileno"
"flock" "fork" "format" "formline" "getc" "getgrent" "getgrgid" "getgrnam"
"gethostbyaddr" "gethostbyname" "gethostent" "getlogin" "getnetbyaddr"
"getnetbyname" "getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar"
"seek" "seekdir" "select" "semctl" "semget" "semop" "send" "setgrent"
"sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent"
"setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite"
"shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice" "split"
"sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink"
"syscall" "sysopen" "sysread" "sysseek" "system" "syswrite" "tell"
"telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AnyDBM_File" "App::Prove" "App::Prove::State" "App::Prove::State::Result"
"App::Prove::State::Result::Test" "Archive::Extract" "Archive::Tar"
"Archive::Tar::Constant" "Archive::Tar::File" "Archive::Zip"
"Archive::Zip::Archive" "Archive::Zip::BufferedFileHandle"
"Archive::Zip::DirectoryMember" "Archive::Zip::FAQ"
"Archive::Zip::FileMember" "Archive::Zip::Member"
"Archive::Zip::MemberRead" "Archive::Zip::MockFileHandle"
"Archive::Zip::NewFileMember" "Archive::Zip::StringMember"
"Archive::Zip::Tree" "Archive::Zip::ZipFileMember" "Attribute::Handlers"
"AutoLoader" "AutoSplit" "B" "B::BUtils" "B::Concise" "B::Debug"
"B::Deparse" "B::Lint" "B::Lint::Debug" "B::Module::Info" "B::Showlex"
"B::Terse" "B::Xref" "Benchmark" "Binfmt::Format" "Binfmt::Lib"
"Bundle::DBD::mysql" "Bundle::DBI" "Bundle::LWP" "Bundle::PlRPC" "CGI"
"CGI::Apache" "CGI::Carp" "CGI::Cookie" "CGI::Pretty" "CGI::Push"
"CGI::Switch" "CGI::Util" "CORE" "CPAN" "CPAN::API::HOWTO" "CPAN::Author"
"CPAN::Bundle" "CPAN::CacheMgr" "CPAN::Complete" "CPAN::Debug"
"CPAN::DeferredCode" "CPAN::Distribution" "CPAN::Distroprefs"
"CPAN::Distrostatus" "CPAN::Exception::RecursiveDependency"
"CPAN::Exception::blocked_urllist" "CPAN::Exception::yaml_not_installed"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HandleConfig"
"CPAN::Index" "CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent"
"CPAN::Module" "CPAN::Nox" "CPAN::Prompt" "CPAN::Queue" "CPAN::Shell"
"CPAN::Tarzip" "CPAN::URL" "CPAN::Version" "CPANPLUS" "CPANPLUS::Backend"
"CPANPLUS::Backend::RV" "CPANPLUS::Config" "CPANPLUS::Config::System"
"CPANPLUS::Configure" "CPANPLUS::Configure::Setup" "CPANPLUS::Dist"
"CPANPLUS::Dist::Autobundle" "CPANPLUS::Dist::Base" "CPANPLUS::Dist::Build"
"CPANPLUS::Dist::Build::Constants" "CPANPLUS::Dist::MM"
"CPANPLUS::Dist::Sample" "CPANPLUS::Error" "CPANPLUS::FAQ"
"CPANPLUS::Hacking" "CPANPLUS::Internals" "CPANPLUS::Internals::Constants"
"CPANPLUS::Internals::Constants::Report" "CPANPLUS::Internals::Extract"
"CPANPLUS::Internals::Fetch" "CPANPLUS::Internals::Report"
"CPANPLUS::Internals::Search" "CPANPLUS::Internals::Source"
"CPANPLUS::Internals::Source::Memory" "CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::HOWTO"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Carp" "Carp::Heavy"
"Class::ISA" "Class::Struct" "Compress::Raw::Bzip2" "Compress::Raw::Zlib"
"Compress::Zlib" "Config" "Config::Extensions" "Cwd" "DB" "DBD::DBM"
"DBD::ExampleP" "DBD::File" "DBD::Gofer" "DBD::Gofer::Policy::Base"
"DBD::Gofer::Policy::classic" "DBD::Gofer::Policy::pedantic"
"DBD::Gofer::Policy::rush" "DBD::Gofer::Transport::Base"
"DBD::Gofer::Transport::null" "DBD::Gofer::Transport::pipeone"
"DBD::Gofer::Transport::stream" "DBD::NullP" "DBD::Proxy" "DBD::Sponge"
"DBD::mysql" "DBD::mysql::GetInfo" "DBI" "DBI::Changes"
"DBI::Const::GetInfo::ANSI" "DBI::Const::GetInfo::ODBC"
"DBI::Const::GetInfoReturn" "DBI::Const::GetInfoType" "DBI::DBD"
"DBI::DBD::Metadata" "DBI::FAQ" "DBI::Gofer::Execute" "DBI::Gofer::Request"
"DBI::Gofer::Response" "DBI::Gofer::Serializer::Base"
"DBI::Gofer::Serializer::DataDumper" "DBI::Gofer::Serializer::Storable"
"DBI::Gofer::Transport::Base" "DBI::Gofer::Transport::pipeone"
"DBI::Gofer::Transport::stream" "DBI::Profile" "DBI::ProfileData"
"DBI::ProfileDumper" "DBI::ProfileDumper::Apache" "DBI::ProfileSubs"
"DBI::ProxyServer" "DBI::PurePerl" "DBI::Roadmap" "DBI::SQL::Nano"
"DBI::Util::CacheMemory" "DBI::Util::_accessor" "DBI::W32ODBC" "DBM_Filter"
"DBM_Filter::compress" "DBM_Filter::encode" "DBM_Filter::int32"
"DBM_Filter::null" "DBM_Filter::utf8" "DB_File" "Data::Dumper"
"Date::Format" "Date::Language" "Date::Language::Afar"
"Date::Language::Amharic" "Date::Language::Austrian"
"Date::Language::Brazilian" "Date::Language::Chinese"
"Date::Language::Chinese_GB" "Date::Language::Czech"
"Date::Language::Danish" "Date::Language::Dutch" "Date::Language::English"
"Date::Language::Finnish" "Date::Language::French" "Date::Language::Gedeo"
"Date::Language::German" "Date::Language::Greek"
"Date::Language::Hungarian" "Date::Language::Icelandic"
"Date::Language::Italian" "Date::Language::Norwegian"
"Date::Language::Oromo" "Date::Language::Romanian"
"Date::Language::Russian" "Date::Language::Russian_cp1251"
"Date::Language::Russian_koi8r" "Date::Language::Sidama"
"Date::Language::Somali" "Date::Language::Spanish"
"Date::Language::Swedish" "Date::Language::Tigrinya"
"Date::Language::TigrinyaEritrean" "Date::Language::TigrinyaEthiopian"
"Date::Language::Turkish" "Date::Parse" "Debconf::AutoSelect"
"Debconf::Base" "Debconf::Client::ConfModule" "Debconf::ConfModule"
"Debconf::Config" "Debconf::Db" "Debconf::DbDriver"
"Debconf::DbDriver::Backup" "Debconf::DbDriver::Cache"
"Debconf::DbDriver::Copy" "Debconf::DbDriver::Debug"
"Debconf::DbDriver::DirTree" "Debconf::DbDriver::Directory"
"Debconf::DbDriver::File" "Debconf::DbDriver::LDAP"
"Debconf::DbDriver::PackageDir" "Debconf::DbDriver::Pipe"
"Debconf::DbDriver::Stack" "Debconf::Element"
"Debconf::Element::Dialog::Boolean" "Debconf::Element::Dialog::Error"
"Debconf::Element::Dialog::Multiselect" "Debconf::Element::Dialog::Note"
"Debconf::Element::Dialog::Password" "Debconf::Element::Dialog::Progress"
"Debconf::Element::Dialog::Select" "Debconf::Element::Dialog::String"
"Debconf::Element::Dialog::Text" "Debconf::Element::Editor::Boolean"
"Debconf::Element::Editor::Error" "Debconf::Element::Editor::Multiselect"
"Debconf::Element::Editor::Note" "Debconf::Element::Editor::Password"
"Debconf::Element::Editor::Progress" "Debconf::Element::Editor::Select"
"Debconf::Element::Editor::String" "Debconf::Element::Editor::Text"
"Debconf::Element::Gnome" "Debconf::Element::Gnome::Boolean"
"Debconf::Element::Gnome::Error" "Debconf::Element::Gnome::Multiselect"
"Debconf::Element::Gnome::Note" "Debconf::Element::Gnome::Password"
"Debconf::Element::Gnome::Progress" "Debconf::Element::Gnome::Select"
"Debconf::Element::Gnome::String" "Debconf::Element::Gnome::Text"
"Debconf::Element::Multiselect" "Debconf::Element::Noninteractive"
"Debconf::Element::Noninteractive::Boolean"
"Debconf::Element::Noninteractive::Error"
"Debconf::Element::Noninteractive::Multiselect"
"Debconf::Element::Noninteractive::Note"
"Debconf::Element::Noninteractive::Password"
"Debconf::Element::Noninteractive::Progress"
"Debconf::Element::Noninteractive::Select"
"Debconf::Element::Noninteractive::String"
"Debconf::Element::Noninteractive::Text" "Debconf::Element::Select"
"Debconf::Element::Teletype::Boolean" "Debconf::Element::Teletype::Error"
"Debconf::Element::Teletype::Multiselect"
"Debconf::Element::Teletype::Note" "Debconf::Element::Teletype::Password"
"Debconf::Element::Teletype::Progress" "Debconf::Element::Teletype::Select"
"Debconf::Element::Teletype::String" "Debconf::Element::Teletype::Text"
"Debconf::Element::Web::Boolean" "Debconf::Element::Web::Error"
"Debconf::Element::Web::Multiselect" "Debconf::Element::Web::Note"
"Debconf::Element::Web::Password" "Debconf::Element::Web::Progress"
"Debconf::Element::Web::Select" "Debconf::Element::Web::String"
"Debconf::Element::Web::Text" "Debconf::Encoding" "Debconf::Format"
"Debconf::Format::822" "Debconf::FrontEnd" "Debconf::FrontEnd::Dialog"
"Debconf::FrontEnd::Editor" "Debconf::FrontEnd::Gnome"
"Debconf::FrontEnd::Noninteractive" "Debconf::FrontEnd::Passthrough"
"Debconf::FrontEnd::Readline" "Debconf::FrontEnd::ScreenSize"
"Debconf::FrontEnd::Teletype" "Debconf::FrontEnd::Text"
"Debconf::FrontEnd::Web" "Debconf::Gettext" "Debconf::Iterator"
"Debconf::Log" "Debconf::Priority" "Debconf::Question" "Debconf::Template"
"Debconf::Template::Transient" "Debconf::TmpFile" "Debian::AdduserCommon"
"Debian::DebConf::Client::ConfModule" "Debian::Debhelper::Buildsystem"
"Debian::Debhelper::Buildsystem::ant"
"Debian::Debhelper::Buildsystem::autoconf"
"Debian::Debhelper::Buildsystem::cmake"
"Debian::Debhelper::Buildsystem::makefile"
"Debian::Debhelper::Buildsystem::perl_build"
"Debian::Debhelper::Buildsystem::perl_makemaker"
"Debian::Debhelper::Buildsystem::python_distutils"
"Debian::Debhelper::Buildsystem::qmake"
"Debian::Debhelper::Dh_Buildsystems" "Debian::Debhelper::Dh_Getopt"
"Debian::Debhelper::Dh_Lib" "Debian::Debhelper::Dh_Version"
"Debian::Debhelper::Sequence::bash_completion"
"Debian::Debhelper::Sequence::dkms"
"Debian::Debhelper::Sequence::python_central"
"Debian::Debhelper::Sequence::python_support" "Debian::Defoma::Common"
"Debian::Defoma::Font" "Debian::Defoma::FontCache" "Debian::Defoma::Id"
"Debian::Defoma::IdCache" "Debian::Defoma::Subst"
"Debian::Defoma::SubstCache" "Debian::Defoma::User"
"Debian::DictionariesCommon" "Debian::DocBase::Common"
"Debian::DocBase::DB" "Debian::DocBase::DocBaseFile"
"Debian::DocBase::Document" "Debian::DocBase::Gettext"
"Debian::DocBase::InstallDocs" "Debian::DocBase::Programs::Dhelp"
"Debian::DocBase::Programs::Dwww" "Debian::DocBase::Programs::Scrollkeeper"
"Debian::DocBase::Utils" "DebianNet" "Devel::DProf" "Devel::InnerPackage"
"Devel::PPPort" "Devel::Peek" "Devel::SelfStubber" "Digest" "Digest::MD5"
"Digest::SHA" "Digest::SHA1" "Digest::base" "Digest::file" "DirHandle"
"Dpkg" "Dpkg::Arch" "Dpkg::BuildOptions" "Dpkg::Changelog"
"Dpkg::Changelog::Debian" "Dpkg::Changelog::Entry"
"Dpkg::Changelog::Entry::Debian" "Dpkg::Changelog::Parse" "Dpkg::Checksums"
"Dpkg::Compression" "Dpkg::Conf" "Dpkg::Control" "Dpkg::Control::Changelog"
"Dpkg::Control::Fields" "Dpkg::Control::Hash" "Dpkg::Control::Info"
"Dpkg::Control::Types" "Dpkg::Deps" "Dpkg::ErrorHandling" "Dpkg::Exit"
"Dpkg::Gettext" "Dpkg::IPC" "Dpkg::Index" "Dpkg::Path" "Dpkg::Shlibs"
"Dpkg::Shlibs::Objdump" "Dpkg::Shlibs::Symbol" "Dpkg::Shlibs::SymbolFile"
"Dpkg::Source::Archive" "Dpkg::Source::CompressedFile"
"Dpkg::Source::Compressor" "Dpkg::Source::Functions"
"Dpkg::Source::Package" "Dpkg::Source::Package::V1"
"Dpkg::Source::Package::V2" "Dpkg::Source::Package::V3::bzr"
"Dpkg::Source::Package::V3::custom" "Dpkg::Source::Package::V3::git"
"Dpkg::Source::Package::V3::native" "Dpkg::Source::Package::V3::quilt"
"Dpkg::Source::Patch" "Dpkg::Substvars" "Dpkg::Vars" "Dpkg::Vendor"
"Dpkg::Vendor::Debian" "Dpkg::Vendor::Default" "Dpkg::Vendor::Ubuntu"
"Dpkg::Version" "Dumpvalue" "DynaLoader" "Encode" "Encode::Alias"
"Encode::Byte" "Encode::CJKConstants" "Encode::CN" "Encode::CN::HZ"
"Encode::Config" "Encode::EBCDIC" "Encode::Encoder" "Encode::Encoding"
"Encode::GSM0338" "Encode::Guess" "Encode::JP" "Encode::JP::H2Z"
"Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Error" "Error::Simple" "Exporter" "Exporter::Heavy"
"ExtUtils::CBuilder" "ExtUtils::CBuilder::Base"
"ExtUtils::CBuilder::Platform::Unix" "ExtUtils::CBuilder::Platform::VMS"
"ExtUtils::CBuilder::Platform::Windows" "ExtUtils::CBuilder::Platform::aix"
"ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::Manifest" "ExtUtils::Miniperl" "ExtUtils::Mkbootstrap"
"ExtUtils::Mksymlists" "ExtUtils::Packlist" "ExtUtils::ParseXS"
"ExtUtils::testlib" "Fatal" "Fcntl" "File::Basename" "File::CheckTree"
"File::Compare" "File::Copy" "File::Copy::Recursive" "File::DosGlob"
"File::Fetch" "File::Find" "File::Glob" "File::GlobMapper" "File::Listing"
"File::Path" "File::Spec" "File::Spec::Cygwin" "File::Spec::Epoc"
"File::Spec::Functions" "File::Spec::Mac" "File::Spec::OS2"
"File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32" "File::Temp"
"File::stat" "FileCache" "FileHandle" "Filter::Simple" "Filter::Util::Call"
"FindBin" "Font::AFM" "Font::FreeType" "Font::FreeType::Face"
"Font::FreeType::Glyph" "Font::Metrics::Courier"
"Font::Metrics::CourierBold" "Font::Metrics::CourierBoldOblique"
"Font::Metrics::CourierOblique" "Font::Metrics::Helvetica"
"Font::Metrics::HelveticaBold" "Font::Metrics::HelveticaBoldOblique"
"Font::Metrics::HelveticaOblique" "Font::Metrics::TimesBold"
"Font::Metrics::TimesBoldItalic" "Font::Metrics::TimesItalic"
"Font::Metrics::TimesRoman" "Foomatic::DB" "Foomatic::Defaults"
"Foomatic::PPD" "Foomatic::UIElem" "FreezeThaw" "GDBM_File" "Getopt::Long"
"Getopt::Std" "Git" "HTML::AsSubs" "HTML::Element"
"HTML::Element::traverse" "HTML::Entities" "HTML::Filter" "HTML::Form"
"HTML::FormatPS" "HTML::FormatRTF" "HTML::FormatText" "HTML::Formatter"
"HTML::HeadParser" "HTML::LinkExtor" "HTML::Parse" "HTML::Parser"
"HTML::PullParser" "HTML::Tagset" "HTML::Template" "HTML::TokeParser"
"HTML::Tree" "HTML::Tree::AboutObjects" "HTML::Tree::AboutTrees"
"HTML::Tree::Scanning" "HTML::TreeBuilder" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "Hash::Util"
"Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "I18N::Langinfo" "IO"
"IO::Compress::Adapter::Bzip2" "IO::Compress::Adapter::Deflate"
"IO::Compress::Adapter::Identity" "IO::Compress::Base"
"IO::Compress::Base::Common" "IO::Compress::Bzip2" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants"
"IO::Compress::RawDeflate" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle" "IO::Pipe"
"IO::Poll" "IO::Seekable" "IO::Select" "IO::Socket" "IO::Socket::INET"
"IO::Socket::UNIX" "IO::Uncompress::Adapter::Bunzip2"
"IO::Uncompress::Adapter::Identity" "IO::Uncompress::Adapter::Inflate"
"IO::Uncompress::AnyInflate" "IO::Uncompress::AnyUncompress"
"IO::Uncompress::Base" "IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Zlib" "IPC::Cmd" "IPC::Msg" "IPC::Open2"
"IPC::Open3" "IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "Image::Magick"
"LWP" "LWP::Authen::Basic" "LWP::Authen::Digest" "LWP::Authen::Ntlm"
"LWP::ConnCache" "LWP::Debug" "LWP::DebugFile" "LWP::MediaTypes"
"LWP::MemberMixin" "LWP::Protocol" "LWP::Protocol::GHTTP"
"LWP::Protocol::cpan" "LWP::Protocol::data" "LWP::Protocol::file"
"LWP::Protocol::ftp" "LWP::Protocol::gopher" "LWP::Protocol::http"
"LWP::Protocol::http10" "LWP::Protocol::https" "LWP::Protocol::https10"
"LWP::Protocol::loopback" "LWP::Protocol::mailto" "LWP::Protocol::nntp"
"LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple" "LWP::UserAgent"
"List::Util" "List::Util::PP" "List::Util::XS" "Locale::Constants"
"Locale::Country" "Locale::Currency" "Locale::Language" "Locale::Maketext"
"Locale::Maketext::Guts" "Locale::Maketext::GutsLoader"
"Locale::Maketext::Simple" "Locale::Maketext::TPJ13" "Locale::Script"
"Locale::gettext" "Log::Message" "Log::Message::Config"
"Log::Message::Handlers" "Log::Message::Item" "Log::Message::Simple"
"MIME::Base64" "MIME::QuotedPrint" "MLDBM"
"MLDBM::Serializer::Data::Dumper" "MLDBM::Serializer::FreezeThaw"
"MLDBM::Serializer::Storable" "Mail::Address" "Mail::Cap" "Mail::Field"
"Mail::Field::AddrList" "Mail::Field::Date" "Mail::Field::Generic"
"Mail::Filter" "Mail::Header" "Mail::Internet" "Mail::Mailer"
"Mail::Mailer::qmail" "Mail::Mailer::rfc822" "Mail::Mailer::sendmail"
"Mail::Mailer::smtp" "Mail::Mailer::smtps" "Mail::Mailer::testfile"
"Mail::Send" "Mail::Util" "Math::BigFloat" "Math::BigFloat::Trace"
"Math::BigInt" "Math::BigInt::Calc" "Math::BigInt::CalcEmu"
"Math::BigInt::FastCalc" "Math::BigInt::Trace" "Math::BigRat"
"Math::Complex" "Math::Trig" "Memoize" "Memoize::AnyDBM_File"
"Memoize::Expire" "Memoize::ExpireFile" "Memoize::ExpireTest"
"Memoize::NDBM_File" "Memoize::SDBM_File" "Memoize::Storable"
"Module::Build" "Module::Build::API" "Module::Build::Authoring"
"Module::Build::Base" "Module::Build::Compat" "Module::Build::Config"
"Module::Build::ConfigData" "Module::Build::Cookbook"
"Module::Build::Dumper" "Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Info" "Module::Load" "Module::Load::Conditional" "Module::Loaded"
"Module::Pluggable" "Module::Pluggable::Object" "NDBM_File" "NEXT"
"Net::Cmd" "Net::Config" "Net::Daemon" "Net::Daemon::Log"
"Net::Daemon::Test" "Net::Domain" "Net::FTP" "Net::FTP::A" "Net::FTP::E"
"Net::FTP::I" "Net::FTP::L" "Net::FTP::dataconn" "Net::HTTP"
"Net::HTTP::Methods" "Net::HTTP::NB" "Net::HTTPS" "Net::NNTP" "Net::Netrc"
"Net::POP3" "Net::Ping" "Net::SMTP" "Net::Time" "Net::hostent"
"Net::libnetFAQ" "Net::netent" "Net::protoent" "Net::servent" "O"
"ODBM_File" "Object::Accessor" "Opcode" "POSIX" "Package::Constants"
"PadWalker" "Params::Check" "Parse::CPAN::Meta" "PerlIO" "PerlIO::encoding"
"PerlIO::scalar" "PerlIO::via" "PerlIO::via::QuotedPrint" "Pod::Checker"
"Pod::Escapes" "Pod::Find" "Pod::Functions" "Pod::Html" "Pod::InputObjects"
"Pod::LaTeX" "Pod::Man" "Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser"
"Pod::Perldoc" "Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText"
"Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Plainer"
"Pod::Select" "Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "RPC::PlClient"
"RPC::PlClient::Comm" "RPC::PlServer" "RPC::PlServer::Comm"
"RPC::PlServer::Test" "Roadmap" "SDBM_File" "Safe" "Scalar::Util"
"Scalar::Util::PP" "Search::Dict" "SelectSaver" "SelfLoader" "Sepia"
"Sepia::CPAN" "Sepia::Debug" "Sepia::Xref" "Shell" "Socket" "Storable"
"Sub::Uplevel" "Switch" "Symbol" "Sys::Hostname" "Sys::Syslog" "TAP::Base"
"TAP::Formatter::Base" "TAP::Formatter::Color" "TAP::Formatter::Console"
"TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Object" "TAP::Parser" "TAP::Parser::Aggregator"
"TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::Source::Perl" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer" "TASKS"
"Term::ANSIColor" "Term::Cap" "Term::Complete" "Term::ReadKey"
"Term::ReadLine" "Term::ReadLine::Perl" "Term::ReadLine::readline"
"Term::UI" "Term::UI::History" "Test" "Test::Builder"
"Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Harness" "Test::More" "Test::Simple"
"Test::Tutorial" "Text::Abbrev" "Text::Balanced" "Text::CharWidth"
"Text::Iconv" "Text::ParseWords" "Text::Soundex" "Text::Tabs" "Text::Wrap"
"Text::WrapI18N" "Thread" "Thread::Queue" "Thread::Semaphore" "Tie::Array"
"Tie::File" "Tie::Handle" "Tie::Hash" "Tie::Hash::NamedCapture"
"Tie::Memoize" "Tie::RefHash" "Tie::Scalar" "Tie::StdHandle"
"Tie::SubstrHash" "Tie::Watch" "Time::HiRes" "Time::Local" "Time::Piece"
"Time::Seconds" "Time::Zone" "Time::gmtime" "Time::localtime" "Time::tm"
"Tk" "Tk::804delta" "Tk::Adjuster" "Tk::After" "Tk::Animation"
"Tk::Balloon" "Tk::Bitmap" "Tk::BrowseEntry" "Tk::Button" "Tk::Canvas"
"Tk::Checkbutton" "Tk::Clipboard" "Tk::CmdLine" "Tk::ColorEditor"
"Tk::Common" "Tk::Compound" "Tk::Config" "Tk::ConfigSpecs" "Tk::Configure"
"Tk::DItem" "Tk::Derived" "Tk::Dialog" "Tk::DialogBox" "Tk::DirTree"
"Tk::Dirlist" "Tk::DragDrop" "Tk::DragDrop::Common"
"Tk::DragDrop::LocalDrop" "Tk::DragDrop::Rect" "Tk::DragDrop::SunConst"
"Tk::DragDrop::SunDrop" "Tk::DragDrop::SunSite" "Tk::DragDrop::XDNDDrop"
"Tk::DragDrop::XDNDSite" "Tk::DropSite" "Tk::DummyEncode" "Tk::English"
"Tk::Entry" "Tk::Error" "Tk::ErrorDialog" "Tk::Event" "Tk::Event::IO"
"Tk::Eventloop" "Tk::FBox" "Tk::FileSelect" "Tk::FloatEntry" "Tk::Font"
"Tk::Frame" "Tk::HList" "Tk::IO" "Tk::IconList" "Tk::Image" "Tk::InputO"
"Tk::Internals" "Tk::ItemStyle" "Tk::JPEG" "Tk::LabEntry" "Tk::LabFrame"
"Tk::LabRadio" "Tk::Label" "Tk::Labelframe" "Tk::Listbox" "Tk::MMtry"
"Tk::MMutil" "Tk::MainWindow" "Tk::MakeDepend" "Tk::Menu" "Tk::Menu::Item"
"Tk::Menubar" "Tk::Menubutton" "Tk::Message" "Tk::More" "Tk::MsgBox"
"Tk::Mwm" "Tk::NBFrame" "Tk::NoteBook" "Tk::Optionmenu" "Tk::PNG"
"Tk::Pane" "Tk::Panedwindow" "Tk::Photo" "Tk::Pixmap" "Tk::Pod"
"Tk::Pod::Cache" "Tk::Pod::FindPods" "Tk::Pod::Search" "Tk::Pod::Search_db"
"Tk::Pod::SimpleBridge" "Tk::Pod::Styles" "Tk::Pod::Text" "Tk::Pod::Tree"
"Tk::Pod::Util" "Tk::Pod::WWWBrowser" "Tk::Pod_usage" "Tk::Popup"
"Tk::Pretty" "Tk::ProgressBar" "Tk::ROText" "Tk::Radiobutton" "Tk::Region"
"Tk::Reindex" "Tk::ReindexedROText" "Tk::ReindexedText" "Tk::Scale"
"Tk::Scrollbar" "Tk::Scrolled" "Tk::Spinbox" "Tk::Stats" "Tk::Submethods"
"Tk::SunConst" "Tk::TList" "Tk::Table" "Tk::Tcl-perl" "Tk::Text"
"Tk::Text::Tag" "Tk::TextEdit" "Tk::TextList" "Tk::TextUndo" "Tk::Tiler"
"Tk::TixGrid" "Tk::Toplevel" "Tk::Trace" "Tk::Tree" "Tk::UserGuide"
"Tk::Widget" "Tk::WidgetDemo" "Tk::WinPhoto" "Tk::Wm" "Tk::X" "Tk::X11Font"
"Tk::Xlib" "Tk::Xrm" "Tk::after" "Tk::bind" "Tk::bindtags" "Tk::callbacks"
"Tk::chooseColor" "Tk::chooseDirectory" "Tk::composite"
"Tk::demos::LabEnLabRad" "Tk::demos::widget_lib::Ball"
"Tk::demos::widget_lib::Plot" "Tk::demos::widget_lib::WidgetDemo"
"Tk::event" "Tk::exit" "Tk::fileevent" "Tk::focus" "Tk::form"
"Tk::getOpenFile" "Tk::grab" "Tk::grid" "Tk::install" "Tk::mega"
"Tk::messageBox" "Tk::option" "Tk::options" "Tk::overview" "Tk::pTk"
"Tk::pack" "Tk::palette" "Tk::place" "Tk::selection" "Tk::send" "Tk::tixWm"
"Tk::tkvars" "Tk::widgets" "UNIVERSAL" "URI" "URI::Escape" "URI::Heuristic"
"URI::IRI" "URI::QueryParam" "URI::Split" "URI::URL" "URI::WithBase"
"URI::_foreign" "URI::_generic" "URI::_idna" "URI::_ldap" "URI::_login"
"URI::_punycode" "URI::_query" "URI::_segment" "URI::_server"
"URI::_userpass" "URI::data" "URI::file" "URI::file::Base" "URI::file::FAT"
"URI::file::Mac" "URI::file::OS2" "URI::file::QNX" "URI::file::Unix"
"URI::file::Win32" "URI::ftp" "URI::gopher" "URI::http" "URI::https"
"URI::ldap" "URI::ldapi" "URI::ldaps" "URI::mailto" "URI::mms" "URI::news"
"URI::nntp" "URI::pop" "URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu"
"URI::sip" "URI::sips" "URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270"
"URI::urn" "URI::urn::isbn" "URI::urn::oid" "UUID" "Unicode::Collate"
"Unicode::Normalize" "Unicode::UCD" "User::grent" "User::pwent"
"WWW::RobotRules" "WWW::RobotRules::AnyDBM_File" "Win32::DBIODBC"
"XML::LibXML" "XML::LibXML::Attr" "XML::LibXML::Boolean"
"XML::LibXML::CDATASection" "XML::LibXML::Comment" "XML::LibXML::Common"
"XML::LibXML::DOM" "XML::LibXML::Document" "XML::LibXML::DocumentFragment"
"XML::LibXML::Dtd" "XML::LibXML::Element" "XML::LibXML::ErrNo"
"XML::LibXML::Error" "XML::LibXML::InputCallback" "XML::LibXML::Literal"
"XML::LibXML::Namespace" "XML::LibXML::Node" "XML::LibXML::NodeList"
"XML::LibXML::Number" "XML::LibXML::PI" "XML::LibXML::Parser"
"XML::LibXML::Pattern" "XML::LibXML::Reader" "XML::LibXML::RegExp"
"XML::LibXML::RelaxNG" "XML::LibXML::SAX" "XML::LibXML::SAX::Builder"
"XML::LibXML::SAX::Generator" "XML::LibXML::SAX::Parser"
"XML::LibXML::Schema" "XML::LibXML::Text" "XML::LibXML::XPathContext"
"XML::LibXML::XPathExpression" "XML::LibXSLT" "XML::NamespaceSupport"
"XML::Parser" "XML::Parser::Expat" "XML::Parser::Style::Debug"
"XML::Parser::Style::Objects" "XML::Parser::Style::Stream"
"XML::Parser::Style::Subs" "XML::Parser::Style::Tree" "XML::SAX"
"XML::SAX::Base" "XML::SAX::Debian" "XML::SAX::DocumentLocator"
"XML::SAX::Exception" "XML::SAX::Intro" "XML::SAX::ParserFactory"
"XML::SAX::PurePerl" "XML::SAX::PurePerl::DTDDecls"
"XML::SAX::PurePerl::DebugHandler" "XML::SAX::PurePerl::DocType"
"XML::SAX::PurePerl::EncodingDetect" "XML::SAX::PurePerl::Exception"
"XML::SAX::PurePerl::NoUnicodeExt" "XML::SAX::PurePerl::Productions"
"XML::SAX::PurePerl::Reader" "XML::SAX::PurePerl::Reader::NoUnicodeExt"
"XML::SAX::PurePerl::Reader::Stream" "XML::SAX::PurePerl::Reader::String"
"XML::SAX::PurePerl::Reader::URI" "XML::SAX::PurePerl::Reader::UnicodeExt"
"XML::SAX::PurePerl::UnicodeExt" "XML::SAX::PurePerl::XMLDecl" "XSLoader"
"a2p" "attributes" "attrs" "autodie" "autodie::exception"
"autodie::exception::system" "autodie::hints" "autouse" "base" "bigint"
"bignum" "bigrat" "blib" "bytes" "charnames" "constant" "diagnostics"
"encoding" "encoding::warnings" "feature" "fields" "filetest" "if"
"integer" "less" "lib" "locale" "lwpcook" "lwptut" "mro" "open.pod" "ops"
"overload" "overload::numbers" "overloading" "parent" "perl"
"perl5004delta" "perl5005delta" "perl5100delta" "perl5101delta"
"perl561delta" "perl56delta" "perl570delta" "perl571delta" "perl572delta"
"perl573delta" "perl581delta" "perl582delta" "perl583delta" "perl584delta"
"perl585delta" "perl586delta" "perl587delta" "perl588delta" "perl589delta"
"perl58delta" "perl590delta" "perl591delta" "perl592delta" "perl593delta"
"perl594delta" "perl595delta" "perlaix" "perlamiga" "perlapi" "perlapio"
"perlapollo" "perlartistic" "perlbeos" "perlbook" "perlboot" "perlbot"
"perlbs2000" "perlcall" "perlce" "perlcheat" "perlclib" "perlcn"
"perlcommunity" "perlcompile" "perlcygwin" "perldata" "perldbmfilter"
"perldebguts" "perldebtut" "perldebug" "perldelta" "perldgux" "perldiag"
"perldoc" "perldos" "perldsc" "perlebcdic" "perlembed" "perlepoc" "perlfaq"
"perlfaq1" "perlfaq2" "perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6"
"perlfaq7" "perlfaq8" "perlfaq9" "perlfilter" "perlfork" "perlform"
"perlfreebsd" "perlfunc" "perlglossary" "perlgpl" "perlguts" "perlhack"
"perlhaiku" "perlhist" "perlhpux" "perlhurd" "perlintern" "perlintro"
"perliol" "perlipc" "perlirix" "perljp" "perlko" "perllexwarn" "perllinux"
"perllocale" "perllol" "perlmachten" "perlmacos" "perlmacosx" "perlmint"
"perlmod" "perlmodinstall" "perlmodlib" "perlmodstyle" "perlmpeix"
"perlmroapi" "perlnetware" "perlnewmod" "perlnumber" "perlobj" "perlop"
"perlopenbsd" "perlopentut" "perlos2" "perlos390" "perlos400" "perlothrtut"
"perlpacktut" "perlperf" "perlplan9" "perlpod" "perlpodspec" "perlport"
"perlpragma" "perlqnx" "perlre" "perlreapi" "perlrebackslash"
"perlrecharclass" "perlref" "perlreftut" "perlreguts" "perlrepository"
"perlrequick" "perlreref" "perlretut" "perlriscos" "perlrun" "perlsec"
"perlsolaris" "perlstyle" "perlsub" "perlsymbian" "perlsyn" "perlthrtut"
"perltie" "perltoc" "perltodo" "perltooc" "perltoot" "perltrap" "perltru64"
"perltw" "perlunicode" "perlunifaq" "perluniintro" "perlunitut" "perlutil"
"perluts" "perlvar" "perlvmesa" "perlvms" "perlvos" "perlwin32" "perlxs"
"perlxstut" "re" "sigtrap" "sort.pod" "strict" "subs" "threads"
"threads::shared" "utf8" "vars" "version" "version::Internals" "vmsish"
"warnings" "warnings::register"))
